- stunnel/stunnel.ml
For outbound connections from XAPI, this commit implements the
recommendation from the Citrix security team that XenServer should
use only ciphersuite TLS_RSA_WITH_AES_128_CBC_SHA for TLSv1.2.
(The exception is when the host ssl-legacy setting is switched on for
backward compatibility).
This recommendation is based on a combination of criteria:
* technical (security) considerations
* legal considerations
* compatibility with third-party TLSv1.2 clients
This commit relies on a corresponding commit in another repository to
set the ciphersuite accepted for incoming connections to xapi, so that
XenServer hosts will be able to communicate with one another.
> CP-13189 TLS ciphersuite TLS_RSA_WITH_AES_128_CBC_SHA

- Makefile
The "oasis setup.ml -uninstall" command isn't doing what we need, so
fall back to using ocamlfind directly.
Signed-off-by: David Scott <dave.scott@eu.citrix.com>
> Fix "make uninstall" and "make reinstall"

- stunnel/stunnel.ml
- stunnel/stunnel.mli
Now the Stunnel module needs to have the ciphersuites specified from
outside using set_good_ciphersuites and set_legacy_ciphersuites.
> CP-14531: Configurable stunnel TLS ciphersuites

- stunnel/stunnel.ml
This lets any program using the Stunnel module make outgoing connections
to xapi. At the moment xcp-rrdd does not set any outbound cyphersuites
so it cannot archive rrds.
This is a temporary patch to fix VM shutdown on a slave, pending a
config file based solution.
> CA-197035: Set a default cyphersuite for outgoing connections

- http-svr/buf_io.ml
- http-svr/buf_io.mli
- http-svr/http_svr.ml
In read_body, if we know the length we want to read, just read it. This avoids
the possibility of reading too much in Buf_io.really_input_buf and accidentally
discarding the excess.
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>
> CA-245559: read_body: don't use Buf_io if unnecessary

- http-svr/http.ml
- http-svr/http.mli
This is for use in https://github.com/xapi-project/xen-api/pull/3105 . And in general, I think in all our HTTP handlers, we should have a catch-all case to catch all unmatched exceptions and return this status code there. This would make sure that the client is notified when a random exception happens that we do not explicitly handle. Not responding to the client in case of an error could cause it to hang, see CA-253489 and CA-226886.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
> http-svr: add 500 Internal Server Error HTTP status code

- http-svr/client_server_test.sh
- http-svr/http.ml
- http-svr/http_svr.ml
- http-svr/jbuild
- http-svr/mime.ml
As done in `http_client.ml:69`
These changes were added to the PR later and not pushed to the internal branch,
so they were not part of the tested library. This was breaking the parsing of the
http headers in `http_svr.ml`.
> http-svr: use fields with the right semantics

- xml-light2/xml.ml
This should hopefully solve the remaining issues.
It's annoying that `xml-light2` does not have unit tests, but if we drop the necessity of the xapi-client `Legacy` module, we can drop `xml-light2` as well. So I will not spend time on the tests for the moment.
> xml-light2: fix typo after refactoring

- stunnel/stunnel_cache.ml
This commit is to increase the max_stunnel value when we support larger
number of hosts(64 etc) in a pool.
Signed-off-by: Taoyong Ding <taoyong.ding@citrix.com>
> CP-26298: Increase the max_stunnel in xapi

- http-svr/xmlrpc_client.ml
- http-svr/xmlrpc_client.mli
It would be way better to be using select rather than blocking
reads, but that's a much bigger change and this will need to be
backported.
Also there's a new mechanism for breaking out of the retry loop
if a host has been marked as dead, which will require a change
in xapi to be used.
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> CA-285840: Make sure stunnel doesn't hang talking to dead hosts

- http-svr/xmlrpc_client.ml
Disable debug log level for brand 'mscgen'
Signed-off-by: Min Li <min.li1@citrix.com>
> CA-296532: mpathalert log spam

- stunnel/stunnel.ml
The order of cipher suites need change base on the latest REQ.
Signed-off-by: Min Li <min.li1@citrix.com>
> CP-29696: Change the order of cipher base on latest requirement

- .travis.yml
```
export allow_failures=[{:env=>
/home/travis/.travis/job_stages: eval: line 104: syntax error near unexpected token `newline'
/home/travis/.travis/job_stages: eval: line 104: `export allow_failures=[{:env=>
```
Although we use it the way it is documented here: https://docs.travis-ci.com/user/customizing-the-build/
Looks like they were just indented incorrectly
> allow_failures cannot be parsed by travis

- http-svr.opam
- http-svr/dune
- http-svr/http.ml
- http-svr/ws_helpers.ml
Instead use base64 >= 3.1.0
This causes the parsing code to be more strict: instead of ignoring control characters on the base64 encoded auth token they produce an unknown auth object.
This allows us to drop xapi-stdext-base64 from the codebase
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> maintenance: remove use of xapi-stdext-base64

- .travis.yml
- dune-project
- http-svr.opam
This mutes warnings from Dune like the following:
```
dune build --profile=release
File "xen-api-libs-transitional/http-svr/dune", line 7, characters 14-36:
7 |   (preprocess (pps ppx_deriving_rpc))
^^^^^^^^^^^^^^^^^^^^^^
Warning: .merlin generated is inaccurate. Cannot mix preprocessed and non preprocessed specificiations.
```
> Mute Dune preprocess warnings

- http-svr/server_io.ml
Remove debug log output that is not informative and creates a lot of
output.
> Remove debug logging about accepting connection

- .travis.yml
- http-svr/xmlrpc_client.ml
- http-svr/xmlrpc_client.mli
I've put this into xmlrpc_client.ml(i), alongside `XML_protocol` and
`XMLRPC_protocol`. The filename does not really make sense anymore, but
changing it would cause a lot of updates (it is used all over the place). And
`XML_protocol` us not XMLRPC either... Not worth doing for a "legacy" module.
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>
> CA-336258: http-svr: add JSONRPC_protocol

- .travis.yml
- xml-light2.opam
We missed this one on #80. Not sure how the tests [passed](https://travis-ci.org/github/xapi-project/xen-api-libs-transitional/builds/705425605) for the PR.
> ci: do not pin xenctrlext when running travis

- .ocamlformat
- Makefile
- dune-project
- http-svr.opam
- http-svr/buf_io.ml
- http-svr/buf_io.mli
- http-svr/dune
- http-svr/http.ml
- http-svr/http.mli
- http-svr/http_client.ml
- http-svr/http_proxy.ml
- http-svr/http_svr.ml
- http-svr/http_test.ml
- http-svr/radix_tree.ml
- http-svr/xmlrpc_client.ml
- stunnel.opam
- stunnel/dune
- stunnel/stunnel.ml
- stunnel/stunnel_cache.ml
I've also included the configuration to use ocamlformat so we can format code when we deem necessary,
> Remove stdext's monadic usages

- http-svr/http_svr.ml
The HTTP server prints to stderr but should never do that and use a
logging function. We suspect that this is causing CA-342856.
> CA-342856 don't print to stderr, use Debug.error

- http-svr/http.ml
- http-svr/http.mli
- http-svr/http_svr.ml
- http-svr/http_test.ml
Here we propagate PROXY information in request headers into values of type `Http.Request.t`. We expect the PROXY header to be added by stunnel in the HTTPS case, whenever we set `protocol = proxy`
> CP-35026 parse stunnel PROXY header in http-svr

- stunnel.opam
- stunnel/dune
Place (implicit_transitive_deps false) in dune-project to figure out
which dependencies are incorrect
> maintenance: fix stunnel deps

- http-svr/xmlrpc_client.ml
- stunnel.opam
- stunnel/dune
- stunnel/stunnel.ml
- stunnel/stunnel.mli
- stunnel/stunnel_cache.ml
- stunnel/stunnel_cache.mli
Previously we exposed cert verification with the `verify_cert` parameter to `Stunnel.with_connect`. This was never actually used by the Citrix Hypervisor, so associated code wasn't being properly maintained. 
Here we update that code which modifies the stunnel client config, and expose cert verification via `Stunnel.set_verify_tls_certs` instead; this way we avoid having to endow each call to `with_connect` with a `verify_cert` flag.
This PR breaks xapi, and which is fixed in this PR: https://github.com/xapi-project/xen-api/pull/4247
> Expose cert verification from stunnel library via global flag

- http-svr/xmlrpc_client.ml
- http-svr/xmlrpc_client.mli
This parameter was used exclusively by xapi to establish connections to WLB servers.
The parameter controlling these kinds of connections is being deprecated and the paramter in its usage remove to make it compatible with this change.
I'm drafting this until the xen-api change is ready.
> CP-35584: remove unused parameter to enable per-connection tls verification

- http-svr/xmlrpc_client.ml
- http-svr/xmlrpc_client.mli
- stunnel/stunnel.ml
- stunnel/stunnel.mli
- stunnel/stunnel_cache.ml
- stunnel/stunnel_cache.mli
Our stunnel client library will now create a connection with verification if either the global flag is set, or we specifically ask for a particular connection to have verification (`let verified = Stunnel.get_verify_tls_certs () || verify_cert` - the former is the global flag and the latter is the local flag).
The only client which uses this `verify_cert` parameter is WLB, so this changes ensures that the Pool.wlb_verify_cert flag works as expected. See https://github.com/xapi-project/xen-api/pull/4278 - these PRs should be merged simultaneously
> REQ-403 ensure Pool.wlb_verify_cert flag still works

- http-svr/http_svr.ml
Backport of d9c4b0d e0f7d7d
The HTTP server prints to stderr but should never do that and use a
logging function. We suspect that this is causing CA-342856.
> UPD-666 CA-342856 don't print to stderr, use Debug.error

- .ocamlformat
- stunnel/stunnel.ml
Make stunnel clients verify the connection by asking for the server certificate. This only works with the public server certificate present on the client, which is currently not the default. Hence, this is behind a feature flag.
This is a draft because I still need to test it manually but want to give reviewers a heads up what is coming.
> CP-36095 configure Stunnel SNI for client connections

- stunnel/stunnel.mli
- stunnel/stunnel_cache.ml
- stunnel/stunnel_cache.mli
- expose verification ctl file path, so that xapi can
touch/rm this when appropriate. this is the global default
- make sure we can override the global default with a ?verify_cert
parameter. This is mostly already plumbed
> CP-36340 REQ-403 global, overridable tls verification flag

- stunnel/stunnel.ml
- stunnel/stunnel.mli
The log level is set to debug, which involve lots of logs fillup partition
This commit reset the log level to warning
Signed-off-by: Lin Liu <lin.liu@citrix.com>
> CA-353388: [XSI-989] stunnel sub-process logs fillup partition

- dune-project
- http-svr/dune
- http-svr/http.ml
- http-svr/http_client.ml
- http-svr/http_proxy.ml
- http-svr/http_svr.ml
- http-svr/http_test.ml
- http-svr/mime.ml
- http-svr/radix_tree_test.ml
- http-svr/server_io.ml
- http-svr/test_client.ml
- http-svr/test_server.ml
- http-svr/ws_helpers.ml
- http-svr/xMLRPC.ml
- http-svr/xmlrpc_client.ml
- pciutil/pciutil.ml
- resources/table.ml
- resources/test/safe_test.ml
- resources/test/unixfd_test.ml
- resources/unixfd.ml
- sexpr/dune
- sexpr/sExpr.ml
- sexpr/sExpr_TS.ml
- stunnel/stunnel.ml
- stunnel/stunnel_cache.ml
- uuid/uuid.ml
- xapi-compression/dune
- xapi-compression/xapi_compression.ml
- xml-light2/xml.ml
Previously it always stated zcat file while ignoring the actual name of
the executable used. Now it's taken into account when generating the
error. The error is now logged instead of output to stderr.
This also contains tweaks to the dune metadata, making it less reliable
on implicit dependencies. The merlin approximate mode is not needed
because .merlin files aren't generated anymore.Previously it always stated zcat file while ignoring the actual name of
the executable used. Now it's taken into account when generating the
error. The error is now logged instead of output to stderr.
This also contains tweaks to the dune metadata, making it less reliable
on implicit dependencies. The merlin approximate mode is not needed
because .merlin files aren't generated anymore.
> xapi-compression: change misleading error message
