xapi-project/xen-api-libs-transitional

- http-svr/ws_helpers.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Return the correct protocol

- .travis.yml
- ChangeLog
- _oasis
- gzip/gzip.ml
- http-svr/http.ml
- http-svr/http_client.ml
- http-svr/http_proxy.ml
- http-svr/http_svr.ml
- http-svr/mime.ml
- http-svr/radix_tree.ml
- http-svr/server_io.ml
- http-svr/ws_helpers.ml
- http-svr/xMLRPC.ml
- http-svr/xMLRPC.mli
- http-svr/xmlrpc_client.ml
- opam
- pciutil/pciutil.ml
- sexpr/sExpr.ml
- sexpr/sExpr_TS.ml
- sha1/sha1sum.ml
- stunnel/stunnel.ml
- stunnel/stunnel_cache.ml
- xenstore/watch.ml
- xml-light2/xml.ml
- xml-light2/xml.mli
> Use packed stdext

- _oasis
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Add unix dependency to uuid

- ChangeLog
- _oasis
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Prepare to release v1.0.1

- .travis.yml
> update travis to use the new xs-opam

- .travis.yml
- README.md
- _oasis
- http-svr/http_test.ml
- opam
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
> Enable Http_test tests and coverage

- xapi-libs-transitional.opam
> xapi-libs-transitional: run all tests when testing in Travis

- http-svr/xmlrpc_client.ml
> http-svr: make again safe-string compliant after last PR

- xml-light2/xml.ml
Signed-off-by: Richard Davies <richard.davies@citrix.com>
> CA-291012 Added better printing of xml exc

- http-svr/jbuild
> Simplify PPX processing

- stunnel/stunnel.ml
Signed-off-by: Kun Ma <kun.ma@citrix.com>
> CP-29015: Set correct ciphers for stunnel client

- stunnel/stunnel.ml
- stunnel/stunnel.mli
BVT: 94758 passed
Support test: SR 94766 passed, except
* one known license issue CA-283861 (since 2018-02-17), sub job 2288809
* one sub job 2288820 still in running which needs for 24+ hours
> Feature/req 226/cc backport havana

- http-svr/http_svr.mli
Signed-off-by: Min Li<min.li1@citrix.com>
> BP CA-299944:Add 'response_badrequest' in Havana

- .travis.yml
- gzip.opam
- http-svr.opam
- pciutil.opam
- sexpr.opam
- sha1.opam
- stunnel.opam
- uuid.opam
- xapi-libs-transitional.opam
- xenctrlext.opam
- xml-light2.opam
The title says it:
* update opam files for Opam 2
* update the Travis setup to use xs-opam
> Update Opam and Travis

- http-svr/test_client.ml
Backport of 5774358.
Signed-off-by: Yang Qian <yang.qian@citrix.com>
> XSI-312 CA-289145: Close socket if error occurs when connecting

- .travis.yml
- xapi-libs-transitional.opam
Ounit dependency was missing.
Also updated to the new standard way of setting the travis environment.
> Fix testing in travis

- http-svr/http.ml
Signed-off-by: lippirk <ben.anson@citrix.com>
> CA-329836 Improve logging

- stunnel/dune
- stunnel/stunnel.ml
- stunnel/stunnel.mli
- stunnel/stunnel_cache.ml
Don't allow clients to modify the ciphers used
Signed-off-by: lippirk <ben.anson@citrix.com>
> CP-32840 drop legacy ssl support

- .gitignore
- _tags
- http-svr/xmlrpc_client.ml
- http-svr/xmlrpc_client.mli
> CA-336258: http-svr: add JSONRPC_protocol

- .travis.yml
- http-svr/dune
- http-svr/test_client.ml
- http-svr/xmlrpc_client.ml
- resources/.ocamlformat
- resources/dune
- resources/safe.ml
- resources/safe.mli
- resources/table.ml
- resources/test/dune
- resources/test/safe_test.ml
- resources/test/test.ml
- resources/test/unixfd_test.ml
- resources/unixfd.ml
- resources/unixfd.mli
- safe-resources.opam
- stunnel/dune
- stunnel/stunnel.ml
- stunnel/stunnel.mli
- stunnel/stunnel_cache.ml
- stunnel/stunnel_cache.mli
- xapi-compression.opam
- xapi-compression/dune
- xapi-compression/xapi_compression.ml
- xapi-libs-transitional.opam
A simpler alternative to https://github.com/xapi-project/xen-api-libs-transitional/pull/77
> CA-337546: resource leak handling

- http-svr/http_svr.ml
> backport! (stockholm) CA-342856

- http-svr/ws_helpers.ml
master PR: https://github.com/xapi-project/xen-api-libs-transitional/pull/101
> [stockholm] backport CA-339702
